### ISSUE TITLE
Förslag på lab

### ISSUE THREAD

**Issue by johansundstrom** [johansundstrom/gitlab#11]
1) https://github.com/johansundstrom/github_cheatsheet/blob/master/1_versioning.md#lab-1
2) https://github.com/johansundstrom/github_cheatsheet/blob/master/2_collaboration.md#samarbeten---branchmerge
3) https://github.com/johansundstrom/github_cheatsheet/blob/master/3_remotes.md#lab-3

**Comment by johansundstrom** [comment]
gör gärna en check på att ni genomfört ovanstående punkter och vad ni tycker om dem

**Comment by sorenandersson** [comment]
Har gjort alla tre. Har ett par mindre synpunkter. Är dock i Trollhättan nu o mina anteckningar är hemma. Jag återkommer med feedback.

**Comment by jonperra** [comment]
Vi är digitala här...;-)

**Comment by jonperra** [comment]
Har gjort justeringar i filen 1_versioning.md då jag testade kommandon som inte fungerade. Ligger för påseende i denna stund.
